"""add_domain_id_to_briefing

Revision ID: 22fa2c9e30a4
Revises: d90d5efbc1cc
Create Date: 2026-08-19 11:32:05.620568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fa2c9e30a4'
down_revision: Union[str, None] = 'd90d5efbc1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_landscape_briefings', sa.Column('domain_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'threat_landscape_briefings', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_landscape_briefings', type_='foreignkey')
    op.drop_column('threat_landscape_briefings', 'domain_id')
    # ### end Alembic commands ###
