"""update_risk_schema

Revision ID: 4cad9e1f149f
Revises: 65e16573115f
Create Date: 2026-07-21 10:54:15.992130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cad9e1f149f'
down_revision: Union[str, None] = '65e16573115f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('rule_key', sa.String(length=100), nullable=False))
    op.add_column('risks', sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('risks', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('risks', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('uq_risk_asset_rule', 'risks', ['asset_id', 'rule_key'])
    op.drop_constraint(op.f('risks_asset_id_fkey'), 'risks', type_='foreignkey')
    op.drop_constraint(op.f('risks_check_id_fkey'), 'risks', type_='foreignkey')
    op.drop_constraint(op.f('risks_organization_id_fkey'), 'risks', type_='foreignkey')
    op.create_foreign_key(None, 'risks', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'risks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('risks', 'recommendation')
    op.drop_column('risks', 'check_id')
    op.drop_column('risks', 'title')
    op.drop_column('risks', 'impact')
    op.drop_column('risks', 'detected_at')
    op.drop_column('risks', 'description')
    op.drop_column('risks', 'rule_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('rule_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('risks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('risks', sa.Column('impact', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('risks', sa.Column('check_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.create_foreign_key(op.f('risks_organization_id_fkey'), 'risks', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('risks_check_id_fkey'), 'risks', 'checks', ['check_id'], ['id'])
    op.create_foreign_key(op.f('risks_asset_id_fkey'), 'risks', 'assets', ['asset_id'], ['id'])
    op.drop_constraint('uq_risk_asset_rule', 'risks', type_='unique')
    op.alter_column('risks', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('risks', 'last_seen_at')
    op.drop_column('risks', 'first_detected_at')
    op.drop_column('risks', 'rule_key')
    # ### end Alembic commands ###
