"""Add risk_technique_map

Revision ID: 56f1ad7cf61a
Revises: 9df2d8b3c327
Create Date: 2026-08-15 19:05:17.406703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f1ad7cf61a'
down_revision: Union[str, None] = '9df2d8b3c327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
