"""add_next_check_due_at

Revision ID: 775e16ce9461
Revises: a9e104891e94
Create Date: 2026-07-21 10:28:18.687647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775e16ce9461'
down_revision: Union[str, None] = 'a9e104891e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('next_check_due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'next_check_due_at')
    # ### end Alembic commands ###
