"""Add score snapshots

Revision ID: 7bd61837f4b0
Revises: 4cad9e1f149f
Create Date: 2026-07-21 13:01:40.824788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd61837f4b0'
down_revision: Union[str, None] = '4cad9e1f149f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score_global', sa.Integer(), nullable=False),
    sa.Column('score_dns', sa.Integer(), nullable=False),
    sa.Column('score_tls', sa.Integer(), nullable=False),
    sa.Column('score_messagerie', sa.Integer(), nullable=False),
    sa.Column('score_services', sa.Integer(), nullable=False),
    sa.Column('score_configuration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', name='uq_org_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_snapshots')
    # ### end Alembic commands ###
