"""Add attack_scenarios_detected

Revision ID: 7cf5ab2947ff
Revises: 4aa727325495
Create Date: 2026-07-22 11:22:18.480123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf5ab2947ff'
down_revision: Union[str, None] = '4aa727325495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
