"""Add active recon state

Revision ID: 90262b23a090
Revises: b266f45d8e9b
Create Date: 2026-07-22 10:21:09.970046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90262b23a090'
down_revision: Union[str, None] = 'b266f45d8e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('active_recon_state', sa.String(length=50), server_default='idle', nullable=False))
    op.add_column('domains', sa.Column('last_active_recon_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'last_active_recon_at')
    op.drop_column('domains', 'active_recon_state')
    # ### end Alembic commands ###
