"""Add MITRE ATT_CK models

Revision ID: 9df2d8b3c327
Revises: 000c62ce10cb
Create Date: 2026-08-15 18:54:09.918374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df2d8b3c327'
down_revision: Union[str, None] = '000c62ce10cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
