"""uq_asset_relations

Revision ID: a68b3e8ac470
Revises: c687d947f293
Create Date: 2026-08-16 16:03:13.478660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68b3e8ac470'
down_revision: Union[str, None] = 'c687d947f293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_asset_relation_source_target', 'asset_relations', ['source_asset_id', 'target_asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_relation_source_target', 'asset_relations', type_='unique')
    # ### end Alembic commands ###
