"""add_http_cert_status

Revision ID: a9e104891e94
Revises: b5ea9a34d155
Create Date: 2026-07-21 10:20:42.586226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e104891e94'
down_revision: Union[str, None] = 'b5ea9a34d155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('cert_status', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('http_redirect_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'http_redirect_status')
    op.drop_column('assets', 'cert_status')
    # ### end Alembic commands ###
