"""verify_domain

Revision ID: b266f45d8e9b
Revises: b4f025f66693
Create Date: 2026-07-22 09:00:02.215498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b266f45d8e9b'
down_revision: Union[str, None] = 'b4f025f66693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('ownership_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('domains', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('domains', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('domains', 'verified_at')
    op.drop_column('domains', 'ownership_verified')
    # ### end Alembic commands ###
