"""add domain verification

Revision ID: b4f025f66693
Revises: 142b3cb9a863
Create Date: 2026-07-21 14:24:56.451820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f025f66693'
down_revision: Union[str, None] = '142b3cb9a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('verification_token', sa.String(length=100), nullable=True))
    op.add_column('domains', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'is_verified')
    op.drop_column('domains', 'verification_token')
    # ### end Alembic commands ###
