"""add_eol_fields

Revision ID: b5ea9a34d155
Revises: 05f0c5369362
Create Date: 2026-07-21 09:59:06.369332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ea9a34d155'
down_revision: Union[str, None] = '05f0c5369362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_eol', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assets', sa.Column('eol_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'eol_since')
    op.drop_column('assets', 'is_eol')
    # ### end Alembic commands ###
