"""Add asset relations and extend scenarios

Revision ID: c687d947f293
Revises: 56f1ad7cf61a
Create Date: 2026-08-16 15:22:19.863843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c687d947f293'
down_revision: Union[str, None] = '56f1ad7cf61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attack_scenarios_detected', sa.Column('likelihood_score', sa.Integer(), nullable=True))
    op.add_column('attack_scenarios_detected', sa.Column('severity_score', sa.Integer(), nullable=True))
    op.add_column('attack_scenarios_detected', sa.Column('kill_chain_stage_reached', sa.Integer(), nullable=True))
    op.add_column('attack_scenarios_detected', sa.Column('kill_chain_total_stages', sa.Integer(), nullable=True))
    op.add_column('attack_scenarios_detected', sa.Column('attack_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('attack_scenarios_detected', sa.Column('relevant_attack_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attack_scenarios_detected', 'relevant_attack_groups')
    op.drop_column('attack_scenarios_detected', 'attack_path')
    op.drop_column('attack_scenarios_detected', 'kill_chain_total_stages')
    op.drop_column('attack_scenarios_detected', 'kill_chain_stage_reached')
    op.drop_column('attack_scenarios_detected', 'severity_score')
    op.drop_column('attack_scenarios_detected', 'likelihood_score')
    # ### end Alembic commands ###
