"""add_changed_from_previous

Revision ID: f7242c2acb0e
Revises: 775e16ce9461
Create Date: 2026-07-21 10:33:35.640939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7242c2acb0e'
down_revision: Union[str, None] = '775e16ce9461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('changed_from_previous', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'changed_from_previous')
    # ### end Alembic commands ###
